name: Manual version Build and Push for RC

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'ECR Tag'
        type: string
        required: true

jobs:
  manual-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.region }}
    steps:
      - name: Checkout
        run: echo ${{ env.IMAGE_TAG }}
